<?php

namespace FA\AbsmanBundle\Entity;

/**
 * ActionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
