<?php

namespace FA\AbsmanBundle\Entity;

/**
 * AppLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppLogRepository extends \Doctrine\ORM\EntityRepository
{
}
