<?php

namespace FA\AbsmanBundle\Entity;

/**
 * CountryAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryAdminRepository extends \Doctrine\ORM\EntityRepository
{


    public function getAdminRoleForTarget($user,$country)
    {
        $query = $this->_em
            ->createQuery('SELECT r.role role FROM FAAbsmanBundle:CountryAdmin a JOIN a.role r WHERE a.country = :country AND a.user = :user')
            ->setParameter('country',$country->getBinId())
            ->setParameter('user', $user->getBinId());

        $query_result = $query->getArrayResult();

        $result = false;
        if (array_key_exists(0,$query_result)) {
            $result = $query_result[0]["role"];
        }
        return $result;
    }


    public function getAdmins($country, $offset, $maxResults, $sort)
    {

        $queryBuilder = $this->createQueryBuilder('a')
            ->select('a.id, u.displayName user, u.id userid, r.id roleid, r.roleName rolename')
            ->leftJoin('a.user', 'u')
            ->leftJoin('a.role', 'r')
            ->where('a.country = :country' )
            ->setParameter('country', $country->getBinId());


        if (!empty($sort)) {
            $sortColumns = array("user"=>"u.displayName","rolename"=>"r.roleName");
            $queryBuilder->orderby($sortColumns[$sort[0]["property"]] , $sort[0]["direction"]);
        } else {
            $queryBuilder->orderby('u.displayName', 'DESC');
        }

        $query = $queryBuilder->getQuery();

        $query->setMaxResults($maxResults);
        $query->setFirstResult($offset);

        return $query->getArrayResult();

    }

    public function getAdminsCount($country)
    {
        $query = $this->_em
            ->createQuery('SELECT COUNT(a) FROM FAAbsmanBundle:CountryAdmin a JOIN a.role r WHERE a.country = :target')
            ->setParameter('target', $country->getBinId());

        return (int) $query->getSingleScalarResult();

    }


    public function isAdminForTarget($user,$country)
    {
        $query = $this->_em
            ->createQuery('SELECT COUNT(a) FROM FAAbsmanBundle:CountryAdmin a WHERE a= :country AND a.user = :user')
            ->setParameter('country',  $country->getBinId())
            ->setParameter('user', $user->getBinId());

        return (bool) $query->getSingleScalarResult() != "0";

    }

    public function removeAdmins($country)
    {
        $query = $this->_em
            ->createQuery('DELETE FROM FAAbsmanBundle:CountryAdmin a WHERE a.country = :country')
            ->setParameter('country', $country->getBinId());

        $query->execute();
        return true;

    }


    public function isAdminWithRoleForUser($currentUser, $accessType, $user)
    {

        $qb1 = $this->createQueryBuilder('ca')
            ->select('count(ca)')
            ->innerJoin('ca.user', 'u', 'with', 'u.id = :currentUser')
            ->leftJoin('ca.country', 'c')
            ->leftJoin('c.companies', 'com')
            ->leftJoin('ca.role', 'r')
            ->where('r.id <= (select ro.id from FAAbsmanBundle:Role ro where ro.role = :accessType)')
            ->andWhere(':user MEMBER OF com.users')
            ->setParameter('currentUser',$currentUser->getBinId())
            ->setParameter('accessType',$accessType)
            ->setParameter('user',$user->getBinId());

        $query1 = $qb1->getQuery();

        return (int) $query1->getSingleScalarResult() > 0;

    }
    /*
*/

    public function isAdminWithRoleForCountry($currentUser, $accessType, $country)
    {

      /*
       * /
          $qb1 = $this->createQueryBuilder('ca')
            ->select('u.displayName, r.id,  c.countryName, r.role')
            ->innerJoin('ca.user', 'u', 'with', 'u.id = :currentUser')
            ->innerJoin('ca.country', 'c' , 'with', 'c.id = :country')
            ->leftJoin('ca.role', 'r')
            ->where('r.id <= (select ro.id from FAAbsmanBundle:Role ro where ro.role = :accessType)')
            ->setParameter('currentUser',$currentUser->getBinId())
            ->setParameter('accessType',$accessType)
            ->setParameter('country',$country->getBinId()); /* */

      /* */
        $qb1 = $this->createQueryBuilder('ca')
            ->select('count(ca)')
            ->innerJoin('ca.user', 'u', 'with', 'u.id = :currentUser')
            ->innerJoin('ca.country', 'c' , 'with', 'c.id = :country')
            ->leftJoin('ca.role', 'r')
            ->where('r.id <= (select ro.id from FAAbsmanBundle:Role ro where ro.role = :accessType)')
            ->setParameter('currentUser',$currentUser->getBinId())
            ->setParameter('accessType',$accessType)
            ->setParameter('country',$country->getBinId()); /* */

        $query1 = $qb1->getQuery();

        //var_dump($query1->getResult());

        return (int) $query1->getSingleScalarResult() > 0;

    }

    public function isAdminWithRoleForCompany($currentUser, $accessType, $company)
    {

        $qb1 = $this->createQueryBuilder('ca')
            ->select('count(ca)')
            ->innerJoin('ca.user', 'u', 'with', 'u.id = :currentUser')
            ->leftJoin('ca.country', 'c')
            ->innerJoin('c.companies', 'com' , 'with', 'com.id = :company')
            ->leftJoin('ca.role', 'r')
            ->where('r.id <= (select ro.id from FAAbsmanBundle:Role ro where ro.role = :accessType)')
            ->setParameter('currentUser',$currentUser->getBinId())
            ->setParameter('accessType',$accessType)
            ->setParameter('company',$company->getBinId());

        $query1 = $qb1->getQuery();

        return (int) $query1->getSingleScalarResult() > 0;

    }

    public function isAdminWithRoleForGroup($currentUser, $accessType, $group)
    {

        $qb1 = $this->createQueryBuilder('ca')
            ->select('count(ca)')
            ->innerJoin('ca.user', 'u', 'with', 'u.id = :currentUser')
            ->leftJoin('ca.country', 'c')
            ->leftJoin('c.companies', 'com')
            ->leftJoin('ca.role', 'r')
            ->where('r.id <= (select ro.id from FAAbsmanBundle:Role ro where ro.role = :accessType)')
            ->andWhere(':group MEMBER OF com.uGroups')
            ->setParameter('currentUser',$currentUser->getBinId())
            ->setParameter('accessType',$accessType)
            ->setParameter('group',$group->getBinId());

        $query1 = $qb1->getQuery();

        return (int) $query1->getSingleScalarResult() > 0;

    }

}
