<?php

namespace FA\AbsmanBundle\Entity;

/**
 * DeletedItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeletedItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
