<?php

namespace FA\AbsmanBundle\Entity;

/**
 * EGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
