<?php

namespace FA\AbsmanBundle\Entity;

/**
 * EGroupMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EGroupMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
