<?php

namespace FA\AbsmanBundle\Entity;

/**
 * LeaveCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaveCategoryRepository extends \Doctrine\ORM\EntityRepository
{


    public function getArrayLeaveCategory($leave)
    {
        $queryBuilder = $this->createQueryBuilder('a')
            ->where('a = :leave' )
            ->setParameter('leave', $leave->getBinId());

        $query = $queryBuilder->getQuery();

        return $query->getArrayResult();
    }



    public function getGroupUnallocated($group)
    {

        $allocated = $this->_em
            ->createQuery('SELECT a.id FROM FAAbsmanBundle:LeaveCategory a JOIN a.groups g WHERE g = :group')
            ->setParameter('group', $group->getBinId());

        $allocIds=array();
        foreach ($allocated->getArrayResult() as $alloc) {
            $allocIds[] = pack('H*',$alloc["id"]);
        }

        if (count($allocIds) > 0) {
            $available = $this->_em
                ->createQuery('SELECT b FROM FAAbsmanBundle:LeaveCategory b WHERE b.company = :company AND b.id NOT IN (:allocIds)')
                ->setParameter('company', $group->getCompany()->getBinId())
                ->setParameter('allocIds', $allocIds);
        }
        else {
            $available = $this->_em
                ->createQuery('SELECT b FROM FAAbsmanBundle:LeaveCategory b WHERE b.company = :company')
                ->setParameter('company', $group->getCompany()->getBinId());
        }

        return $available->getResult();

    }



    public function getUserLeave($userId) {

        $queryBuilder = $this->createQueryBuilder('l')
            ->distinct()
            ->innerJoin('l.groups', 'g')
            ->innerJoin('g.users', 'u', 'with', 'u.id = :user')
            ->setParameter('user',pack('H*',$userId));

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }



    public function hasNewerTimeStampForUser($user, $oldestTimeStamp)
    {

        $queryBuilder = $this->createQueryBuilder('l')
            ->select('count(l)')
            ->innerJoin('l.groups', 'g')
            ->innerJoin('g.users', 'u', 'with', 'u.id = :user')
            ->Where('l.lastUpdate > :oldestDate')
            ->setParameter('user', $user->getBinId())
            ->setParameter('oldestDate', date_create("@$oldestTimeStamp"));

        $query = $queryBuilder->getQuery();

        return (int)$query->getSingleScalarResult() !== 0;
    }


    public function hasNewerTimeStampForCompany($company, $oldestTimeStamp) {

        $queryBuilder = $this->createQueryBuilder('l')
            ->select('count(l)')
            ->innerJoin('l.company', 'c', 'with', 'c.id = :company')
            ->Where('l.lastUpdate > :oldestDate')
            ->setParameter('company',$company->getBinId())
            ->setParameter('oldestDate', date_create("@$oldestTimeStamp"));

        $query = $queryBuilder->getQuery();

        return (int) $query->getSingleScalarResult() !== 0;
    }


    public function getUserLeaveCategory($user) {

        $queryBuilder = $this->createQueryBuilder('l')
            ->select('l.id, l.categoryName name')
            ->distinct()
            ->innerJoin('l.groups', 'g')
            ->innerJoin('g.users', 'u', 'with', 'u.id = :user')
            ->setParameter('user', $user->getBinId());

        $query = $queryBuilder->getQuery();

        return  $query->getArrayResult();
    }

    public function getUserLeaveCategoryDetails($user) {

        $queryBuilder = $this->createQueryBuilder('l')
            ->select('l.id, l.categoryName name, l.maxDays maxvalue, l.autoApprovable autoapprovable, l.justificationNotRequired justificationnotrequired, l.categoryText text')
            ->distinct()
            ->innerJoin('l.groups', 'g')
            ->innerJoin('g.users', 'u', 'with', 'u.id = :user')
            ->orderBy("l.displayOrder")
            ->setParameter('user', $user->getBinId());

        $query = $queryBuilder->getQuery();

        return  $query->getArrayResult();
    }
}
