Actiontypes:
    type: entity
    table: actiontypes
    id:
        actiontypeid:
            type: blob
            nullable: false
            length: 16
            fixed: false
            comment: ''
            default: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
            id: true
            generator:
                strategy: IDENTITY
    fields:
        actiontype:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        actiontypetext:
            type: string
            nullable: false
            length: 512
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
